(function(){
const blank=()=>Object.fromEntries(annexFields.map(f=>[f.key,""]));
function injectLayout(){if(document.getElementById("codex-layout-fix-2"))return;const s=document.createElement("style");s.id="codex-layout-fix-2";s.textContent=`
#sourcesTab .panel-upload{display:grid!important;grid-template-columns:minmax(280px,.82fr) minmax(360px,1.18fr)!important;grid-template-areas:"heading actions" "entry entry" "status status"!important;column-gap:16px!important;align-items:start!important;overflow:hidden!important}
#sourcesTab .panel-upload>.section-heading{grid-area:heading;margin:0 0 8px!important}
#sourcesTab .panel-upload>.source-entry-grid{grid-area:entry;grid-column:1/-1;width:100%;align-items:start!important}
#sourcesTab .panel-upload>.source-meta,#sourcesTab .panel-upload>#extractionSummary{grid-area:status}
.manual-column{display:flex!important;flex-direction:column!important;gap:6px!important;margin-top:0!important;padding-top:0!important}
.manual-column .textarea-label{margin:0!important;line-height:1.1!important}
.upload-box,#manualText{min-height:118px!important}
#manualText{max-height:24vh!important}
.compact-sources-list{max-height:128px!important;overflow:auto!important}
.manual-column .project-facts-wrap{display:block!important;margin-top:6px!important;max-height:42vh!important;overflow:auto!important;padding-right:4px!important}
#sourcesTab>.project-facts-wrap,.panel-upload>.project-facts-wrap{display:none!important}
.sources-actions-row{grid-area:actions!important;display:flex!important;justify-content:flex-end!important;align-items:flex-start!important;gap:8px!important;margin:0 0 8px!important;flex-wrap:wrap!important}
.sources-actions-row button{white-space:nowrap!important}
#evaluateRulesBtn,#downloadRulesBtn{display:none!important}
@media(max-width:900px){#sourcesTab .panel-upload{display:block!important}.project-facts-wrap,.compact-sources-list{max-height:none!important}}
`;document.head.appendChild(s)}
function moveProjectFactsPanel(){const facts=document.querySelector(".project-facts-wrap");const manual=document.querySelector("#sourcesTab .manual-column");if(facts&&manual&&facts.parentElement!==manual)manual.appendChild(facts)}
function moveSourceActions(){const panel=document.querySelector("#sourcesTab .panel-upload");if(!panel)return;let row=panel.querySelector(".sources-actions-row");if(!row){row=document.createElement("div");row.className="button-row sources-actions-row";const heading=panel.querySelector(":scope>.section-heading");heading?.after(row)}["addTextBtn","extractBtn","openAutotestBtn","resetBtn"].forEach(id=>{const btn=document.getElementById(id);if(btn&&btn.parentElement!==row)row.appendChild(btn)});["evaluateRulesBtn","downloadRulesBtn"].forEach(id=>document.getElementById(id)?.remove())}
function applyLayout(){injectLayout();moveProjectFactsPanel();moveSourceActions()}
const FRAME_FALLBACK=Object.freeze({normal:[["1. Caracteristicile constructiei sau amenajarii",["denumire_obiectiv","beneficiar","adresa","func\u021biuni","categoria_importanta","tip_cladire","tip_parcaj","caracteristici_dimensionale","numar_utilizatori","autoevacuare","capacitati_depozitare"]],["2. Identificarea si stabilirea nivelurilor de risc de incendiu",["risc_incendiu","surse_aprindere_specifice","procese_substante"]],["3. Nivelurile criteriilor de performanta privind securitatea la incendiu",["stabilitate_foc","limitare_vecinatati","evacuare","interventie"]],["4. Echiparea si dotarea cu instalatii cu rol de securitate la incendiu",["instala\u021bii_stingere","idsai","desfumare","alimentare_electrica","iluminat_siguranta","trsnet"]],["5. Masuri tehnico-organizatorice privind exploatarea constructiei",["m\u0103suri_organizatorice","stingatoare"]],["6. Masuri compensatorii propuse",["m\u0103suri_compensatorii"]]],preliminary:[["1. Caracteristicile constructiei sau amenajarii",["denumire_obiectiv","beneficiar","adresa","func\u021biuni","tip_cladire","caracteristici_dimensionale","numar_utilizatori"]],["2. Nivelurile riscului de incendiu estimat",["risc_incendiu","capacitati_depozitare","surse_aprindere_specifice"]],["3. Nivelurile criteriilor de performanta privind securitatea la incendiu",["stabilitate_foc","evacuare","limitare_vecinatati"]],["4. Instalatii cu rol in asigurarea cerintei securitate la incendiu",["instala\u021bii_stingere","idsai","desfumare","iluminat_siguranta","trsnet"]],["5. Masuri compensatorii",["m\u0103suri_compensatorii"]]]});
let READONLY_FRAME=FRAME_FALLBACK;
if(typeof fetch==="function")fetch("ssi-frame-readonly.json",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(j=>{if(j&&Array.isArray(j.normal)&&Array.isArray(j.preliminary))READONLY_FRAME=Object.freeze(j)}).catch(()=>{});
const labelFor=k=>annexFields.find(f=>f.key===k)?.label||String(k).replace(/_/g," ");
const stripSrc=v=>String(v||"").replace(/\s*\[sursa:[^\]]+\]\s*/gi,"").trim();
function lawLink(ref,label){return`[[LAWREF:${ref}]]${label||ref}[[/LAWREF]]`}
function cleanValue(data,key){return stripSrc(data?.[key])||"De completat din memoriul proiectului activ."}
function buildCleanSsiMarkdown(type="normal"){const data=state.data||blank(),frame=READONLY_FRAME[type]||FRAME_FALLBACK[type],title=type==="preliminary"?"SCENARIU DE SECURITATE LA INCENDIU PRELIMINAR":"SCENARIU DE SECURITATE LA INCENDIU";const lines=[`# ${title}`,"","Cadru generat curat pentru proiectul activ. Structura este incarcata din fisierul read-only `ssi-frame-readonly.json` si completata numai cu datele acestui proiect.","",`Baza metodologica: ${lawLink("act:omai_180_2022","OMAI nr. 180/2022")}; verificari tehnice corelate cu ${lawLink("act:p118_1_2025","P 118/1-2025")}, ${lawLink("act:p118_2_2013","P 118/2-2013")}, ${lawLink("act:p118_3_2015","P 118/3-2015")} si ${lawLink("act:i7_2011","I7-2011")}.`,""];frame.forEach(([section,keys])=>{lines.push(`## ${section}`);keys.forEach(k=>lines.push(`- ${labelFor(k)}: ${cleanValue(data,k)}`));if(section.startsWith("2."))lines.push("- Incadrarea finala se confirma prin calculul sarcinii termice, functiune, materiale combustibile si conditiile de exploatare ale proiectului activ.");if(section.startsWith("3."))lines.push(`- Conformarea se verifica pe articolele aplicabile din ${lawLink("act:p118_1_2025","P 118/1-2025")} si, unde este cazul, pe reglementarile specifice fiecarei instalatii.`);lines.push("")});if(Array.isArray(state.applicableActs)&&state.applicableActs.length){lines.push("## Acte legislative detectate pentru proiect");state.applicableActs.forEach(a=>lines.push(`- ${lawLink(`act:${a.id}`,a.title||a.id)}: ${a.reason||a.why||"act aplicabil proiectului activ"}`));lines.push("")}return lines.join("\n")}
function buildCleanSsiHtml(type="normal"){const md=buildCleanSsiMarkdown(type);const body=typeof markdownToHtml==="function"?markdownToHtml(md,"html"):md.split(/\n+/).map(x=>`<p>${escapeHtml(x)}</p>`).join("");return`<!DOCTYPE html><html lang="ro"><head><meta charset="utf-8"><title>${type==="preliminary"?"SSI preliminar":"SSI normal"}</title><style>body{font-family:Calibri,Arial,sans-serif;font-size:11pt;line-height:1.35;color:#111;margin:12mm 14mm 12mm 21mm}h1{text-align:center;font-size:16pt}h2{font-size:13pt;margin-top:12pt}li{margin:2pt 0}</style></head><body>${body}</body></html>`}
function setCleanReports(){const p=getActiveProject?.();if(!p)return;ensureExtractionTabs?.(p);normalReportOutput.value=buildCleanSsiMarkdown("normal");preliminaryReportOutput.value=buildCleanSsiMarkdown("preliminary");p.normalReport=normalReportOutput.value;p.preliminaryReport=preliminaryReportOutput.value}
function resetRuntimeBlank(keepSources=false){const src=keepSources?safeClone(state.sources||[]):[];state.sources=src;state.data=blank();state.projectProfile=getDefaultProjectProfile();state.applicableActs=[];state.complianceChecks=[];state.rulesCoverage=[];state.actCoverageChecks=[];normalReportOutput.value="";preliminaryReportOutput.value="";if(!keepSources&&manualText)manualText.value="";renderFields();renderProfile();refreshFieldValues();refreshProfileValues();refreshCounters();renderIssuesOutput()}
function wipeProjectRecord(project,keepSources=false){if(!project)return;project.sources=keepSources?safeClone(project.sources||[]):[];project.data=blank();project.projectProfile=getDefaultProjectProfile();project.applicableActs=[];project.complianceChecks=[];project.rulesCoverage=[];project.actCoverageChecks=[];project.normalReport="";project.preliminaryReport="";if(!keepSources)project.manualDraft="";project.openTabs=["sourcesTab"];project.activeTab="sourcesTab";Object.assign(project,{selectedFilesPreview:getDefaultProjectUiState().selectedFilesPreview,uiStatus:getDefaultProjectUiState().uiStatus,extractionSummary:getDefaultProjectUiState().extractionSummary})}
const nativeRenderDocLikePreview=renderDocLikePreview;renderDocLikePreview=function(type){const target=getReportPreviewByType?.(type);if(!target)return nativeRenderDocLikePreview(type);try{const html=buildCleanSsiHtml(type);const parsed=new DOMParser().parseFromString(html,"text/html");target.innerHTML=`<div class="doc-preview-surface">${parsed.body?parsed.body.innerHTML:html}</div>`}catch(e){console.error(e);nativeRenderDocLikePreview(type)}};
const nativeGenerateReports=generateReportsForActiveProject;generateReportsForActiveProject=function(){try{const p=getActiveProject?.();if(!p)return;setCleanReports();renderDocLikePreview("normal");renderDocLikePreview("preliminary");activateTab("normalTab")}catch(e){console.error(e);nativeGenerateReports()}};
const prevCreateBlank=createBlankProject;createBlankProject=n=>{const p=prevCreateBlank(n);wipeProjectRecord(p,false);return p};
const prevLoad=loadProjectIntoUI;loadProjectIntoUI=id=>{prevLoad(id);applyLayout();setCleanReports();renderDocLikePreview("normal");renderDocLikePreview("preliminary");typeof hideAuto==="function"&&hideAuto()};
const prevExtract=handleExtractData;handleExtractData=async()=>{const id=workspaceState.activeProjectId;if(!state.sources.length)return prevExtract();resetRuntimeBlank(true);await prevExtract();setCleanReports();renderDocLikePreview("normal");renderDocLikePreview("preliminary");saveActiveProjectStateFromUI();persistWorkspace();applyLayout();typeof hideAuto==="function"&&hideAuto()};
resetProjectState=()=>{const p=getActiveProject();if(!p)return;wipeProjectRecord(p,false);resetRuntimeBlank(false);if(fileInput)fileInput.value="";p.dirty=true;activateTab("sourcesTab");refreshUI();applyProjectUiState(p);setCleanReports();renderDocLikePreview("normal");renderDocLikePreview("preliminary");saveActiveProjectStateFromUI();persistWorkspace();applyLayout();typeof hideAuto==="function"&&hideAuto()};
function inferActKeyFromRef(refKey){const ref=String(refKey||"").toLowerCase();if(ref.startsWith("act:"))return resolveActKey(ref.slice(4));const entry=state.legislationArticles?.references?.[normalizeLawRefKey(refKey)];if(entry?.actKey)return resolveActKey(entry.actKey);if(ref.includes("p1183")||ref.includes("p_118_3"))return"p118_3_2015";if(ref.includes("p1182")||ref.includes("p_118_2"))return"p118_2_2013";if(ref.includes("p11899")||ref.includes("p118_99")||ref.includes("p118-99"))return"p118_99";if(ref.includes("p1181")||ref.includes("p118_1"))return"p118_1_2025";if(ref.includes("i7"))return"i7_2011";if(ref.includes("i13"))return"i13_2015";if(ref.includes("hg571"))return"hg_571_2016";if(ref.includes("hg766"))return"hg_766_1997";if(ref.includes("omai163"))return"omai_163_2007";if(ref.includes("180_2022")||ref.includes("omai_180"))return"omai_180_2022";return""}
let fullActsIndexPromise=null;
function getFullActsIndex(){if(!fullActsIndexPromise){fullActsIndexPromise=fetch("legislation-program/full-acts-index.json",{cache:"no-store"}).then(r=>r.ok?r.json():null).catch(()=>null)}return fullActsIndexPromise}
function findTextPosition(text,entry){const candidates=[entry?.location,entry?.label,entry?.excerpt].filter(Boolean).map(x=>String(x).replace(/\s+/g," ").trim()).filter(x=>x.length>5);const normalized=String(text||"").replace(/\s+/g," ");for(const c of candidates){const idx=normalized.toLowerCase().indexOf(c.toLowerCase().slice(0,120));if(idx>=0)return idx}return-1}
function renderFullActText(actKey,record,text,selectedRefKey){const normalizedRef=normalizeLawRefKey(selectedRefKey||"");const entry=state.legislationArticles?.references?.[normalizedRef]||null;const pos=findTextPosition(text,entry);const title=record?.title||state.legislationArticles?.acts?.[actKey]?.title||actKey;const meta=`<article class="rule-card"><strong>${escapeHtml(title)}</strong><div class="source-meta">Act integral din arhiva read-only: ${escapeHtml(record?.textPath||"")}</div>${record?.officialUrl?`<p class="law-inline-note"><strong>Sursa oficiala:</strong> <a href="${escapeHtml(record.officialUrl)}" target="_blank" rel="noreferrer">${escapeHtml(record.officialUrl)}</a></p>`:""}${entry?`<p><strong>Reper selectat:</strong> ${escapeHtml(entry.label||normalizedRef)}</p>`:""}</article>`;let body="";if(pos>=0){const before=text.slice(0,pos),hit=text.slice(pos,pos+500),after=text.slice(pos+500);body=`<pre class="law-fulltext-pre">${escapeHtml(before)}<mark id="law_fulltext_selected" class="is-selected-law-ref">${escapeHtml(hit)}</mark>${escapeHtml(after)}</pre>`}else{body=`<pre class="law-fulltext-pre">${escapeHtml(text)}</pre>`}return `${meta}<article class="rule-card"><strong>Text integral act</strong>${body}</article>`}
async function showReadonlyFullAct(actKey,selectedRefKey){if(!actKey||!lawTabContent||typeof fetch!=="function")return false;const index=await getFullActsIndex();const record=index?.acts?.[actKey];if(!record?.textPath)return false;lawTabContent.innerHTML=`<article class="rule-card"><strong>Se incarca actul integral...</strong><div class="source-meta">${escapeHtml(record.textPath)}</div></article>`;const res=await fetch(record.textPath,{cache:"no-store"});if(!res.ok)return false;const text=await res.text();if(!text.trim())return false;lawTabContent.innerHTML=renderFullActText(actKey,record,text,selectedRefKey);const mark=lawTabContent.querySelector("#law_fulltext_selected");if(mark)mark.scrollIntoView({block:"center"});else lawTabContent.scrollTop=0;return true}
const previousOpenLawModal=openLawModal;openLawModal=function(refKey){let miss="";const ref=typeof normalizeLawRefKey==="function"?normalizeLawRefKey(refKey):String(refKey||"");const actKey=inferActKeyFromRef(ref);const alertBackup=window.alert;window.alert=m=>{miss=String(m||"")};try{previousOpenLawModal(refKey)}finally{window.alert=alertBackup}const p=getActiveProject?.();if(p)ensureProjectTab(p,"lawTab");activateTab("lawTab");if(actKey){showReadonlyFullAct(actKey,ref).catch(()=>{});if(!miss)return}if(!miss)return;if(lawTabHeaderMeta)lawTabHeaderMeta.textContent="Referinta legislativa detectata automat";if(lawTabContent){lawTabContent.innerHTML=`<article class="rule-card"><strong>Referinta legislativa necartografiata inca</strong><div class="source-meta">Cheie referinta: ${escapeHtml(ref)}</div><p>Aplicatia a detectat aceasta trimitere in SSI, dar nu are inca articolul local mapat la textul integral. Verifica actul in sursa oficiala si adauga articolul in baza legislativa locala.</p></article>`;lawTabContent.scrollTop=0}};
window.__ssiCommands={...window.__ssiCommands,newProject:()=>createNewProject(),switchProjectFromSelect:id=>{if(id&&id!==workspaceState.activeProjectId)switchProject(id)},activateWorkspaceTab:id=>activateTab(id),openAutotest:()=>activateTab("autotestTab"),openSources:()=>openProjectTab("sourcesTab"),openFields:()=>openProjectTab("sourcesTab",projectFactsSummary),openLawRef:id=>openLawModal(id),handleFileSelection:e=>handleSelectedFiles(e),addManualText:()=>handleAddManualText(),extractData:()=>handleExtractData(),resetProject:()=>resetProjectState()};
applyLayout();typeof hideAuto==="function"&&hideAuto();if(workspaceState.activeProjectId){setCleanReports();renderDocLikePreview("normal");renderDocLikePreview("preliminary")}
}());
