(function(){
function applyLayoutFix(){if(document.getElementById('codex-layout-fix'))return;const s=document.createElement('style');s.id='codex-layout-fix';s.textContent=`
:root{--ui-density:14px;--ui-tabs-lift:18px;}
.app-bar{position:relative;min-height:58px;}
.app-topline{min-height:28px;padding-top:0;transform:translateY(-2px);}
.app-title{padding-bottom:0;}
.app-bottomline{min-height:22px;padding-bottom:0;margin-top:-5px;margin-bottom:-8px;transform:translateY(-7px);}
.browser-tabs{margin-bottom:calc(-10px - (var(--ui-tabs-lift) / 2));}
.workspace-tabs-dynamic{min-height:20px;}
.browser-tab{top:0;padding:1px 9px 1px;}
.workspace-shell{padding-top:0;}
#sourcesTab.is-active{overflow:hidden;padding-right:0;}
#sourcesTab .layout,#sourcesTab .panel-upload{height:100%;min-height:0;}
#sourcesTab .panel-upload{position:sticky;top:0;overflow:hidden;}
.source-entry-grid{min-height:0;grid-template-columns:minmax(280px,.82fr) minmax(360px,1.18fr);align-items:start;}
.source-column,.manual-column{align-self:start;}
.upload-box{min-height:118px;}
.manual-column{display:flex;flex-direction:column;gap:8px;margin-top:0;}
.manual-column .textarea-label{margin:0 0 2px;line-height:1;}
.compact-sources-list{max-height:128px;overflow:auto;}
#manualText{min-height:118px;max-height:24vh;}
.manual-column .project-facts-wrap{margin-top:4px;min-height:0;max-height:42vh;overflow:auto;padding-right:4px;}
#sourcesTab>.project-facts-wrap,.panel-upload>.project-facts-wrap{display:none;}
@media(max-width:900px){.app-bar{min-height:auto}.app-topline{transform:none}.app-bottomline{transform:none;margin-top:0;margin-bottom:0}#sourcesTab.is-active{overflow:auto}.project-facts-wrap{max-height:none}.compact-sources-list{max-height:none}}
`;document.head.appendChild(s)}
applyLayoutFix();
function moveProjectFactsPanel(){const facts=document.querySelector('.project-facts-wrap');const manual=document.querySelector('#sourcesTab .manual-column');if(facts&&manual&&facts.parentElement!==manual){manual.appendChild(facts)}}
moveProjectFactsPanel();
const blank=()=>Object.fromEntries(annexFields.map(f=>[f.key,""]));
const cl=v=>cleanExtract(String(v||""));
function bind(id,fn){const e=document.getElementById(id);if(!e)return;e.removeAttribute("onclick");e.onclick=null;e.addEventListener("click",ev=>{ev.preventDefault();ev.stopImmediatePropagation();fn(ev)},true)}
function hideAuto(){}
function clear(){state.data=blank();state.projectProfile=getDefaultProjectProfile();state.applicableActs=[];state.complianceChecks=[];state.rulesCoverage=[];state.actCoverageChecks=[];normalReportOutput.value="";preliminaryReportOutput.value="";renderFields();renderProfile();refreshFieldValues();refreshProfileValues();refreshCounters();renderDocLikePreview("normal");renderDocLikePreview("preliminary");renderIssuesOutput()}
function sanitize(p){if(!p)return;p.sources=Array.isArray(p.sources)?safeClone(p.sources):[];p.data={...blank(),...(p.data&&typeof p.data==="object"?p.data:{})};p.projectProfile={...getDefaultProjectProfile(),...(p.projectProfile&&typeof p.projectProfile==="object"?p.projectProfile:{})};p.applicableActs=Array.isArray(p.applicableActs)?safeClone(p.applicableActs):[];p.complianceChecks=Array.isArray(p.complianceChecks)?safeClone(p.complianceChecks):[];p.rulesCoverage=Array.isArray(p.rulesCoverage)?safeClone(p.rulesCoverage):[];p.actCoverageChecks=Array.isArray(p.actCoverageChecks)?safeClone(p.actCoverageChecks):[];p.openTabs=Array.isArray(p.openTabs)?p.openTabs.filter(Boolean):["sourcesTab"];if(!p.openTabs.includes("sourcesTab"))p.openTabs.unshift("sourcesTab")}
function afterColon(line){return cl(String(line||"").replace(/^.*?\s*[:\-]\s*/i,""))}
function direct(lines,re){const line=lines.find(l=>re.test(l));return line?afterColon(line):""}
function section(lines,startRe,stopRe=/^(instalatii|vecinatati|cai|surse|materiale si alcatuiri|telefon|e-mail)/i,limit=4){const out=[];lines.forEach((l,i)=>{if(startRe.test(l)){const a=afterColon(l);if(a&&a!==cl(l))out.push(a);else out.push(l);for(let n=1;n<=limit;n++){const x=lines[i+n]||"";if(!x||stopRe.test(x))break;out.push(x)}}});return Array.from(new Set(out)).map(cl).join(" ")}
customExtractors.denumire_obiectiv=lines=>direct(lines,/\bdenumir(?:ea|e)\s+(?:obiectivului|obiectiv|constructiei|investitiei)\s*[:\-]/i);
customExtractors.beneficiar=lines=>{const v=direct(lines,/(?:beneficiar|proprietar|investitor)\s*[:\-]/i);return v?cleanBeneficiaryText(v):""};
customExtractors.adresa=lines=>{const v=direct(lines,/(?:adresa|amplasament)(?:\s+obiectivului)?\s*[:\-]/i);return v?cleanAddressText(v):""};
customExtractors["func\u021biuni"]=(lines,content)=>{const vals=lines.filter(l=>/(?:destinatia|functiuni(?:\s+principale|\s+secundare)?)/i.test(l)).map(afterColon).filter(Boolean);if(vals.length)return Array.from(new Set(vals.join(", ").split(",").map(s=>s.trim()).filter(Boolean))).join(", ");const t=String(content||"").toLowerCase(),a=[];if(t.includes("comert"))a.push("comert");if(t.includes("restaurant")||t.includes("alimentatie publica"))a.push("alimentatie publica");if(t.includes("productie"))a.push("productie");if(t.includes("depozit"))a.push("depozitare");if(t.includes("birou"))a.push("birouri");if(t.includes("cult"))a.push("cult");return Array.from(new Set(a)).join(", ")};
customExtractors.tip_cladire=(lines,content)=>direct(lines,/tip\s+cladire\s*[:\-]/i)||(()=>{const t=String(content||"").toLowerCase();if(t.includes("parcaj subteran"))return"cladire civila cu parcaj subteran";if(t.includes("productie")||t.includes("industriala"))return"cladire de productie si/sau depozitare";if(t.includes("restaurant")||t.includes("alimentatie publica"))return"cladire civila de alimentatie publica";if(t.includes("comert"))return"cladire civila de comert";return""})();
const norm=v=>String(v||"").replace(/\s*mp\b/i," m2").replace(/\s*mc\b/i," m3").replace(/\s+/g," ").trim();
customExtractors.caracteristici_dimensionale=lines=>{const j=lines.join(" "),reg=j.match(/regim(?:ul)?\s+de\s+inaltime\s*[:\-]?\s*([^;.\n]+)/i)?.[1]?.trim(),h=j.match(/inaltimea?\s+maxima(?:\s+a\s+cladirii)?\s*[:\-]?\s*([0-9][0-9., ]*\s*m)\b/i)?.[1]?.trim(),v=j.match(/volum(?:ul)?(?:\s+construit|\s+constructiei)?\s*[:\-]?\s*([0-9][0-9., ]*\s*(?:m3|mÃƒâ€šÃ‚Â³|mc))\b/i)?.[1]?.trim(),ac=j.match(/aria\s+construit[Ãƒâ€žÃ†â€™a]\s*[:\-]?\s*([0-9][0-9., ]*\s*(?:m2|mÃƒâ€šÃ‚Â²|mp))\b/i)?.[1]?.trim(),ad=j.match(/aria\s+desf[Ãƒâ€žÃ†â€™a][ÃƒË†Ã¢â€žÂ¢s]urat[Ãƒâ€žÃ†â€™a]\s*[:\-]?\s*([0-9][0-9., ]*\s*(?:m2|mÃƒâ€šÃ‚Â²|mp))\b/i)?.[1]?.trim();return[reg?`regim de inaltime: ${reg}`:"",h?`inaltime maxima: ${norm(h)}`:"",v?`volum: ${norm(v)}`:"",ac?`aria construita: ${norm(ac)}`:"",ad?`aria desfasurata: ${norm(ad)}`:""] .filter(Boolean).join("; ")};
customExtractors.capacitati_depozitare=lines=>section(lines,/depozitare|materiale\s+combustibile|materiale\s+depozitate|bucatarie\s+si\s+depozitare/i,/^(surse\s+specifice|instalatii|vecinatati|cai\s+de|materiale\s+si\s+alcatuiri)/i,3);
customExtractors.surse_aprindere_specifice=lines=>section(lines,/surse\s+specifice\s+de\s+aprindere|surse\s+de\s+aprindere/i,/^(memor|instalatii|depozitare|vecinatati|cai\s+de)/i,2);
const oldEv=customExtractors.evacuare;customExtractors.evacuare=(lines,content)=>[oldEv?.(lines,content),section(lines,/cai\s+de\s+circulatie|cai\s+si\s+iesiri|iesiri|case\s+de\s+scara|usi/i,/^(instalatii|depozitare|surse|vecinatati|materiale)/i,3)].filter(Boolean).map(cl).join(" ");
customExtractors.risc_incendiu=(lines,content)=>{const raw=String(content||lines.join(" ")),t=raw.toLowerCase(),p=[],users=extractFirstNumber(raw.match(/num[aÄƒ]r(?:ul)?\s+maxim\s+de\s+utilizatori[^.\n]*/i)?.[0]||"");if(/parcaj\s+(subteran|inchis|ÃƒÆ’Ã‚Â®nchis)|subsol/.test(t))p.push("parcaj/subsol: risc mare de incendiu estimat, de verificat pe compartimentul respectiv");if(/depozit/.test(t)&&/(carton|ambalaj|palet|lemn|pvc|textil|plastic|folie)/.test(t))p.push("depozitare cu materiale combustibile: risc mare estimat pentru zona de depozitare");if(/(sala|salon|evenimente|food-court|aglomerari|aglomerari de persoane|aglomerÄƒri)/.test(t)&&(users===null||users>=200))p.push("aglomerari de persoane: risc si evacuare de verificat pentru incadrarea de sala aglomerata");if(/(productie|fabricatie|prelucr)/.test(t)&&/(vopsele|diluanti|solvent|sudura|utilaje)/.test(t))p.push("productie/mentenanta cu surse tehnologice: risc mijlociu estimat, cu posibile zone locale de risc mare");if(/(bucatarie|preparare calda|gaze naturale|aragaz|cuptoare)/.test(t))p.push("bucatarie/preparare calda: risc mijlociu estimat");if(/(comert|restaurant|alimentatie publica|birou|servicii|cult|sala multifunctionala|evenimente)/.test(t))p.push("spatii civile pentru public/birouri: risc mic estimat, daca sarcina termica si materialele raman uzuale");if(!p.length&&/(beton|zidarie|metal|lemn|utilizatori|aria|volum)/.test(t))p.push("risc de incendiu de stabilit din sarcina termica, destinatie si materialele declarate; date insuficiente pentru incadrare automata sigura");return p.join("; ")};
customExtractors.stabilitate_foc=(lines,content)=>{const t=String(content||lines.join(" ")).toLowerCase(),p=[],con=/(beton armat|stalpi.*beton|grinzi.*beton|plansee.*beton|zidarie|caramida)/.test(t),steel=/(structura metalica.*protejat|otel.*protejat|panouri.*a2|vata minerala|miez incombustibil)/.test(t),wood=/(structura\s+(?:din\s+)?lemn|sarpanta|ÃƒË†Ã¢â€žÂ¢arpantÃƒâ€žÃ†â€™|acoperis[^.\n]*lemn|grinzi[^.\n]*lemn|stalpi[^.\n]*lemn)/.test(t);if(con||steel)p.push("grad de rezistenta la foc estimat: II, daca elementele portante si compartimentarile indeplinesc duratele minime cerute de P118");if(con)p.push("stabilitate: structura din beton armat/zidarie permite incadrare favorabila, cu confirmare prin proiectul de rezistenta");if(steel)p.push("structura metalica/panouri incombustibile: incadrarea depinde de protectia la foc si de clasele declarate ale produselor");if(wood)p.push("elemente structurale din lemn: necesita tratament/clasa de reactie la foc si verificarea influentei asupra gradului de rezistenta");if(!p.length&&/(materiale|structura|pereti|acoperis|plansee)/.test(t))p.push("gradul de rezistenta la foc nu poate fi stabilit complet fara proiectul de rezistenta si clasele de reactie/rezistenta ale elementelor");return p.join("; ")};
syncProfileFromDataHints=function(){const txt=k=>String(state.data[k]||"").toLowerCase(),tip=txt("tip_cladire"),fun=txt("func\u021biuni"),idsai=txt("idsai"),sting=txt("instala\u021bii_stingere"),des=txt("desfumare"),ilu=txt("iluminat_siguranta"),tr=txt("trsnet"),n=extractFirstNumber(state.data.numar_utilizatori);if(!state.projectProfile.buildingClass){if(tip.includes("mixt"))state.projectProfile.buildingClass="mixta";if(tip.includes("depoz"))state.projectProfile.buildingClass="depozitare";if(tip.includes("product"))state.projectProfile.buildingClass="productie";if(tip.includes("civ"))state.projectProfile.buildingClass="civila"}if(!state.projectProfile.occupantCount&&n!==null)state.projectProfile.occupantCount=n;const d=new Set(state.projectProfile.destinations||[]);if(fun.includes("comert"))d.add("comert");if(fun.includes("invat"))d.add("invatamant");if(fun.includes("turis")||fun.includes("cazare"))d.add("turism");if(fun.includes("sanat"))d.add("sanatate");if(fun.includes("cult"))d.add("cult");if(fun.includes("parc"))d.add("parcaj");if(fun.includes("administr"))d.add("administrativa");state.projectProfile.destinations=Array.from(d);if(txt("adresa").includes("demisol")||txt("caracteristici_dimensionale").includes("demisol"))state.projectProfile.hasBasement=true;const ins=new Set(state.projectProfile.installations||[]);if(sting)ins.add("stingere");if(sting.includes("hidrant"))ins.add("hidranti_interiori");if(sting.includes("sprink"))ins.add("sprinklere");if(idsai)ins.add("detectare_alarmare");if(des)ins.add("desfumare");if(ilu)ins.add("iluminat_siguranta");if(tr)ins.add("protectie_trasnet");if(txt("centrala_termica"))ins.add("incalzire_centrala");if(des)ins.add("ventilare_climatizare");state.projectProfile.installations=Array.from(ins)};
const oc=createBlankProject;createBlankProject=n=>{const p=oc(n);sanitize(p);return p};const ol=loadProjectIntoUI;loadProjectIntoUI=id=>{sanitize(getProjectById(id));clear();ol(id);moveProjectFactsPanel();hideAuto()};const oe=handleExtractData;handleExtractData=async()=>{const id=workspaceState.activeProjectId;if(!state.sources.length)return oe();clear();await oe();sanitize(getProjectById(id));saveActiveProjectStateFromUI();persistWorkspace();hideAuto()};const or=resetProjectState;resetProjectState=()=>{or();sanitize(getActiveProject());clear();saveActiveProjectStateFromUI();persistWorkspace();hideAuto()};const oa=activateTab;activateTab=t=>{oa(t);hideAuto()};
const prevOpen=openLawModal;openLawModal=function(refKey){let miss="";const a=window.alert;window.alert=m=>{miss=String(m||"")};try{prevOpen(refKey)}finally{window.alert=a}if(!miss)return;const ref=typeof normalizeLawRefKey==="function"?normalizeLawRefKey(refKey):String(refKey||"");const p=getActiveProject?.();if(p)ensureProjectTab(p,"lawTab");if(lawTabHeaderMeta)lawTabHeaderMeta.textContent="Referinta legislativa detectata automat";if(lawTabContent){lawTabContent.innerHTML=`<article class="rule-card"><strong>Referinta legislativa necartografiata inca</strong><div class="source-meta">Cheie referinta: ${escapeHtml(ref)}</div><p>Aplicatia a detectat aceasta trimitere in SSI, dar nu are inca articolul local mapat la textul integral. Verifica actul in sursa oficiala si adauga articolul in baza legislativa locala.</p></article>`;lawTabContent.scrollTop=0}activateTab("lawTab")};
bind("addTextBtn",()=>handleAddManualText());bind("extractBtn",()=>handleExtractData());bind("resetBtn",()=>resetProjectState());bind("projectAddBtn",()=>createNewProject());bind("menuNewProjectBtn",()=>createNewProject());bind("openSourcesQuickBtn",()=>openProjectTab("sourcesTab"));bind("openFieldsQuickBtn",()=>openProjectTab("sourcesTab",projectFactsSummary));bind("openRulesQuickBtn",()=>{const p=getActiveProject();if(!p){window.alert("Deschide mai intai un proiect nou.");return}ensureProjectTab(p,"legislationTab");openProjectTab("legislationTab")});
const fi=document.getElementById("fileInput");if(fi){fi.removeAttribute("onchange");fi.onchange=null;fi.addEventListener("change",e=>{e.stopImmediatePropagation();handleSelectedFiles(e)},true)}const ps=document.getElementById("projectSelector");if(ps){ps.removeAttribute("onchange");ps.onchange=null;ps.addEventListener("change",e=>{e.stopImmediatePropagation();const id=e.target.value;if(id&&id!==workspaceState.activeProjectId)switchProject(id)},true)}
window.__ssiCommands={...window.__ssiCommands,newProject:()=>createNewProject(),switchProjectFromSelect:id=>{if(id&&id!==workspaceState.activeProjectId)switchProject(id)},activateWorkspaceTab:id=>activateTab(id),openSources:()=>openProjectTab("sourcesTab"),openFields:()=>openProjectTab("sourcesTab",projectFactsSummary),openLawRef:id=>openLawModal(id),handleFileSelection:e=>handleSelectedFiles(e),addManualText:()=>handleAddManualText(),extractData:()=>handleExtractData(),resetProject:()=>resetProjectState()};hideAuto();workspaceState.projects.forEach(sanitize);if(workspaceState.activeProjectId)loadProjectIntoUI(workspaceState.activeProjectId);
}());
