plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vladcoinstal.galeriefotoanimata'
    compileSdk 35

    defaultConfig {
        applicationId 'com.vladcoinstal.galeriefotoanimata'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
